server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: ${LAVALINK_PASSWORD:-youshallnotpass}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE

logging:
  level:
    root: INFO
    lavalink: INFO
