spring:
  cloud:
    consul:
      enabled: false
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
  application:
    version: "@build.version@"
    timestamp: "@build.timestamp@"
    name: "SablebotBot-Worker"
  datasource:

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    overwriteExistingJobs: true
    properties:
      org.quartz.scheduler.instanceName: "sablebot-spring-boot-quartz"
      org.quartz.scheduler.instanceId: "AUTO"
      org.quartz.threadPool.threadCount: "15"
      org.quartz.jobStore.tablePrefix: "qrtz_"
  liquibase:
    change-log: "classpath:db/master.xml"

sablebot:
  worker:
    discord:
      token: ""
      playingStatus: "Suck"
      shardsTotal: 1
    commands:
      invokeLogging: true
    support:
      guild-id: 763252709833965579
      emergency-channel-id: 924575732989034506

server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true